name: Build and exports
on: [push, pull_request]

jobs:
  export-win:
    name: Windows export
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set compiler as x64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Compile
        run: mkdir build && cd build && cmake -GNinja -DCMAKE_BUILD_TYPE=Release .. && ninja
      - name: Debug list file
        run: ls -laR
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows build
          path: Analyzers/lpc_analyzer.dll
          retention-days: 14
